# Generated by Django 5.0.1 on 2024-03-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='art',
            new_name='category',
        ),
    ]
